/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class conexion_ConexionC */

#ifndef _Included_conexion_ConexionC
#define _Included_conexion_ConexionC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     conexion_ConexionC
 * Method:    loadImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_conexion_ConexionC_loadImage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
